export const STRETCHING_ROUTINES = [
  {
    id: 'hamstring',
    name: 'Hamstring Focus',
    icon: '🦵',
    description: 'Targets posterior chain – hamstrings, calves, lower back',
    durationLabel: '~20 min',
    exercises: [
      { id: 'h1', name: 'Standing Forward Fold', duration: '60s', reps: null, notes: 'Soft bend in knees, let gravity work. Breathe into the stretch.' },
      { id: 'h2', name: 'Seated Single-Leg Reach', duration: '45s each', reps: null, notes: 'Keep back flat, hinge from hips not waist.' },
      { id: 'h3', name: 'Supine Hamstring Stretch (strap)', duration: '60s each leg', reps: null, notes: 'Pull leg toward chest, keep opposite leg flat.' },
      { id: 'h4', name: 'Downward Dog Hold', duration: '60s', reps: null, notes: 'Press heels toward floor, pedal slowly.' },
      { id: 'h5', name: 'Romanian Deadlift Stretch', duration: null, reps: '10 slow reps', notes: 'Bodyweight only. Feel the stretch at bottom.' },
      { id: 'h6', name: 'Calf Wall Stretch', duration: '45s each', reps: null, notes: 'Straight leg, then bent knee.' },
      { id: 'h7', name: 'Supine Twist', duration: '45s each side', reps: null, notes: 'Keep shoulders flat on floor.' },
    ],
  },
  {
    id: 'hip',
    name: 'Hip Mobility',
    icon: '🔄',
    description: 'Opens hip flexors, external rotators, and glutes',
    durationLabel: '~25 min',
    exercises: [
      { id: 'hip1', name: '90/90 Hip Stretch', duration: '60s each side', reps: null, notes: 'Keep both glutes on floor. Lean into front shin.' },
      { id: 'hip2', name: 'Pigeon Pose', duration: '90s each side', reps: null, notes: 'Square hips to the mat. Don\'t collapse to one side.' },
      { id: 'hip3', name: 'Couch Stretch', duration: '60s each side', reps: null, notes: 'Drive hip toward floor. Core tight.' },
      { id: 'hip4', name: 'Hip CARs (Controlled Articular Rotations)', duration: null, reps: '5 each direction per side', notes: 'Slow, deliberate circles at max range.' },
      { id: 'hip5', name: 'Deep Squat Hold', duration: '60s', reps: null, notes: 'Heels flat if possible. Use door frame for balance.' },
      { id: 'hip6', name: 'Butterfly / Bound Angle', duration: '60s', reps: null, notes: 'Press knees toward floor with elbows.' },
      { id: 'hip7', name: 'Lateral Lunge Stretch', duration: '45s each side', reps: null, notes: 'Keep grounded foot flat.' },
    ],
  },
  {
    id: 'fullbody',
    name: 'Full Body',
    icon: '🧘',
    description: 'Head-to-toe routine covering all major muscle groups',
    durationLabel: '~35 min',
    exercises: [
      { id: 'fb1', name: 'Neck Rolls', duration: '30s each direction', reps: null, notes: 'Slow and controlled. Stop if any sharp pain.' },
      { id: 'fb2', name: 'Thoracic Spine Rotations', duration: null, reps: '10 each side', notes: 'Seated or on all fours. Reach elbow toward ceiling.' },
      { id: 'fb3', name: 'Doorway Chest Stretch', duration: '45s', reps: null, notes: 'High, mid, and low arm positions.' },
      { id: 'fb4', name: 'Child\'s Pose', duration: '60s', reps: null, notes: 'Walk hands wide for lat stretch.' },
      { id: 'fb5', name: 'Cat-Cow', duration: null, reps: '10 slow reps', notes: 'Sync with breath.' },
      { id: 'fb6', name: 'Hip Flexor Lunge Stretch', duration: '60s each side', reps: null, notes: 'Back knee on pad. Drive hips forward.' },
      { id: 'fb7', name: 'Pigeon Pose', duration: '90s each side', reps: null, notes: '' },
      { id: 'fb8', name: 'Standing Quad Stretch', duration: '30s each', reps: null, notes: 'Pull foot toward glute. Keep knees together.' },
      { id: 'fb9', name: 'Seated Forward Fold', duration: '90s', reps: null, notes: 'Hinge from hips, not rounding from back.' },
      { id: 'fb10', name: 'Calf & Ankle Circles', duration: '30s each foot', reps: null, notes: '' },
    ],
  },
  {
    id: 'postski',
    name: 'Post-Ski Recovery',
    icon: '⛷️',
    description: 'Target ski-specific muscle fatigue: quads, glutes, back, calves',
    durationLabel: '~25 min',
    exercises: [
      { id: 'ps1', name: 'Standing Quad Stretch', duration: '45s each', reps: null, notes: 'Ski boots wreck your quads – go deep.' },
      { id: 'ps2', name: 'Couch Stretch', duration: '90s each side', reps: null, notes: 'Priority #1 after a ski day.' },
      { id: 'ps3', name: 'Downward Dog', duration: '60s', reps: null, notes: 'Pedal heels to loosen calves.' },
      { id: 'ps4', name: 'Supine Glute Stretch (Figure 4)', duration: '60s each side', reps: null, notes: 'Pull knees toward chest.' },
      { id: 'ps5', name: 'Seated Spinal Twist', duration: '45s each side', reps: null, notes: 'Decompress the lumbar spine.' },
      { id: 'ps6', name: 'Calf Wall Stretch', duration: '60s each leg', reps: null, notes: 'Both straight and bent-knee.' },
      { id: 'ps7', name: 'Hip Flexor Lunge', duration: '60s each side', reps: null, notes: 'Snowplow stance taxes hip flexors all day.' },
      { id: 'ps8', name: 'Thoracic Extension over Foam Roller', duration: '60s', reps: null, notes: 'Slow up-and-down along mid back.' },
    ],
  },
  {
    id: 'recovery',
    name: 'Recovery Day',
    icon: '💤',
    description: 'Gentle mobility for rest days – minimal intensity, maximum feel-good',
    durationLabel: '~20 min',
    exercises: [
      { id: 'rd1', name: 'Diaphragmatic Breathing', duration: '3 min', reps: null, notes: '4-7-8 pattern. Activate parasympathetic system.' },
      { id: 'rd2', name: 'Supine Knee-to-Chest Pulls', duration: null, reps: '10 slow reps each side', notes: 'Gentle lower back release.' },
      { id: 'rd3', name: 'Supine Twist', duration: '60s each side', reps: null, notes: 'Arms out wide. Let gravity do the work.' },
      { id: 'rd4', name: 'Child\'s Pose', duration: '2 min', reps: null, notes: 'Full relaxation. No pushing.' },
      { id: 'rd5', name: 'Happy Baby', duration: '60s', reps: null, notes: 'Rock gently side to side.' },
      { id: 'rd6', name: 'Legs Up the Wall', duration: '3 min', reps: null, notes: 'Great for reducing lower leg swelling.' },
      { id: 'rd7', name: 'Neck & Shoulder Rolls', duration: '60s', reps: null, notes: 'Slow and gentle. Release tension.' },
    ],
  },
];
